Repository 7-lin/Final_Project_BE, pull requests merged in 2023-04, with the labels that each got.

#42 fix: Fix CORS Issue
  src/main/java/com/fc/final7/global/security/SecurityConfig.java
Labels: For : Backend, Priority : Ciritical, Status : Completed, Type : Bug

#43 fix: Fix CORS
  src/main/java/com/fc/final7/global/security/SecurityConfig.java
Labels: For : Backend, Priority : Ciritical, Status : Completed, Type : Feature

#44 fix: add origin for frontend
  src/main/java/com/fc/final7/global/security/SecurityConfig.java
Labels: For : Backend, Priority : Medium, Status : Completed, Type : Feature

#57 fix: 비어있는 이미지 목록 검증 로직 수정
  src/main/java/com/fc/final7/domain/review/service/impl/ReviewServiceImpl.java
Labels: For : API, Priority : Medium, Status : Completed, Type : Feature

#58 fix: 후기 작성 시 상품 가져오는 로직 수정
  src/main/java/com/fc/final7/domain/review/service/impl/ReviewServiceImpl.java
Labels: For : API, Priority : Medium, Status : Completed, Type : Feature

#62 refactor: 예외처리 추가했습니다.
  src/main/java/com/fc/final7/domain/reservation/service/impl/ReservationServiceImpl.java
Labels: For : API, For : Backend, Priority : Ciritical, Status : Completed, Type : Feature

#63 fix: Fix Review Total DTO
  src/main/java/com/fc/final7/domain/review/dto/ReviewResponseDTO.java
Labels: For : API, Priority : Medium, Status : Completed, Type : Feature
